version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.302-sdk
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Run the Web Application
          command: dotnet build